[tools]
# mise trust && mise install
node = "latest"
difftastic = "latest"
bitwarden = "latest"
bitwarden-secrets-manager = "latest"
github-cli = "latest"
#terraform = "latest"
#terraform-docs = "latest"